sudo: required
branches:
  only:
    - master
    - /^greenkeeper/.*$/

language: node_js
node_js:
  - "10"
cache:
  directories:
    - node_modules

jobs:
  include:
    - stage: generate feed
      script: npm install && node index.js 